name: Version

on:
  workflow_dispatch:
    inputs:
      runType:
        description: 'Run type'
        required: true
        default: dryrun
        type: choice
        options:
          - dryrun
          - live
      versionBump:
        description: 'Version bump strategy'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
          - custom
      customVersion:
        description: 'Custom version'
        type: string
      versionTag:
        description: 'Version tag'
        required: true
        default: next
        type: choice
        options:
          - next
          - latest
          - custom
      customVersionTag:
        description: 'Custom version tag'
        type: string

jobs:
  Bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Echo variables
        run: |
          echo "versionBump:       ${{ inputs.versionBump }}"
          echo "customVersion:     ${{ inputs.customVersion }}"
          echo "runType:           ${{ inputs.runType }}"
          echo "versionTag:        ${{ inputs.versionTag }}"
          echo "customVersionTag:  ${{ inputs.customVersionTag }}"
      - name: Bump version with Lerna
        run: echo "npx lerna version ${{ inputs.versionBump == 'custom' && inputs.customVersion || inputs.versionBump }} ${{ inputs.runType == 'live' && '--yes' || '--yes --no-git-tag-version --no-push --json' }}"
        # TODO: when publishing add `--dist-tag ${{ inputs.versionTag }}`
      # - run: git diff
